---
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
    name: {{ .Name }}
spec:
    usages:
        - digital signature
        - key encipherment
        - server auth
    request: {{ .Request }}